### ISSUE TITLE
Avaliação N1

### ISSUE THREAD

**Issue by scalabrinig** [An-225/NSU#1]
Parabéns ao Grupo!

O trabalho está muito bom. Tenho apenas um comentário: O requisito O software deve ser capaz de atualizar tarefas importadas do Moodle automaticamente é um requisito funcional.

**Comment by An-225** [comment]
Corrigido na tabela de requisitos da lista consolidada.

[Tabela de requisitos](https://github.com/An-225/NSU/wiki/Levantamento-de-Requisitos#tabela-de-requisitos)
